---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: client
  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.64.tar.gz
  
  tasks:
    - name: update
      apt: update_cache=yes   
      ignore_errors: yes 
   
    - name: Installating JDK.
      apt: name=default-jdk state=latest

    - name: add group tomcat
      group:
        name: tomcat
        state: present 
    - name: add user tomcat 
      user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat createhome=no
    #download the tomcat package
    - name: create a tomcat directory 
      file: 
        path: /usr/share/tomcat 
        state: directory
        owner: tomcat 
        group: tomcat 
    - name: Download tomcat 
      get_url: 
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_location}}"
    
    #extract the tomcat archive
    - name: extract tomcat 
      unarchive:
        src: "{{tomcat_download_location}}"
        dest: /usr/share/tomcat 
        owner: tomcat 
        group: tomcat 
        remote_src: yes 
        extra_opts: [--strip-components=1]
        creates: /usr/share/tomcat/bin 
    - name: Creating service for Apache tomcat.
      file:
        path: /etc/systemd/system/tomcat.service
        state: touch
        mode: u+rwx,g-rwx,o-x

    - name: download foo.conf
      get_url:
        url: https://raw.githubusercontent.com/aftab70/Apache_Tomcat/master/tomcat_services
        dest: /etc/systemd/system/tomcat.service
 
    - name: Deamon reload.
      command: systemctl daemon-reload

    - name: Starting Apache Tomcat service.
      service: name=tomcat state=started